version: "3.8"

services:
  transactional.filesystem.php:
    container_name: transactional.filesystem.php
    build: ./docker/php
    volumes:
      - ./:/app
    restart: unless-stopped
    command: [ "tail", "-f", "/dev/null" ]